component_depth: 1
languages:
- java
- script
exclude:
- ./Documentation/.*
- ./Documentation/images/.*
- ./Documentation/jws/.*
- ./Documentation/tutorial/.*
- ./JavaDoc/.*
- ./JavaDoc/net/.*
- ./JavaDoc/net/n3/.*
- ./JavaDoc/net/n3/nanoxml/.*
- ./JavaDoc/org/.*
- ./JavaDoc/org/jhotdraw/.*
- ./JavaDoc/org/jhotdraw/annotations/.*
- ./JavaDoc/org/jhotdraw/app/.*
- ./JavaDoc/org/jhotdraw/app/action/.*
- ./JavaDoc/org/jhotdraw/app/action/app/.*
- ./JavaDoc/org/jhotdraw/app/action/edit/.*
- ./JavaDoc/org/jhotdraw/app/action/file/.*
- ./JavaDoc/org/jhotdraw/app/action/view/.*
- ./JavaDoc/org/jhotdraw/app/action/window/.*
- ./JavaDoc/org/jhotdraw/app/osx/.*
- ./JavaDoc/org/jhotdraw/beans/.*
- ./JavaDoc/org/jhotdraw/color/.*
- ./JavaDoc/org/jhotdraw/draw/.*
- ./JavaDoc/org/jhotdraw/draw/action/.*
- ./JavaDoc/org/jhotdraw/draw/connector/.*
- ./JavaDoc/org/jhotdraw/draw/decoration/.*
- ./JavaDoc/org/jhotdraw/draw/event/.*
- ./JavaDoc/org/jhotdraw/draw/handle/.*
- ./JavaDoc/org/jhotdraw/draw/io/.*
- ./JavaDoc/org/jhotdraw/draw/layouter/.*
- ./JavaDoc/org/jhotdraw/draw/liner/.*
- ./JavaDoc/org/jhotdraw/draw/locator/.*
- ./JavaDoc/org/jhotdraw/draw/print/.*
- ./JavaDoc/org/jhotdraw/draw/text/.*
- ./JavaDoc/org/jhotdraw/draw/tool/.*
- ./JavaDoc/org/jhotdraw/geom/.*
- ./JavaDoc/org/jhotdraw/gui/.*
- ./JavaDoc/org/jhotdraw/gui/datatransfer/.*
- ./JavaDoc/org/jhotdraw/gui/event/.*
- ./JavaDoc/org/jhotdraw/gui/filechooser/.*
- ./JavaDoc/org/jhotdraw/gui/fontchooser/.*
- ./JavaDoc/org/jhotdraw/gui/plaf/.*
- ./JavaDoc/org/jhotdraw/gui/plaf/palette/.*
- ./JavaDoc/org/jhotdraw/gui/plaf/palette/colorchooser/.*
- ./JavaDoc/org/jhotdraw/io/.*
- ./JavaDoc/org/jhotdraw/net/.*
- ./JavaDoc/org/jhotdraw/samples/.*
- ./JavaDoc/org/jhotdraw/samples/color/.*
- ./JavaDoc/org/jhotdraw/samples/draw/.*
- ./JavaDoc/org/jhotdraw/samples/font/.*
- ./JavaDoc/org/jhotdraw/samples/mini/.*
- ./JavaDoc/org/jhotdraw/samples/net/.*
- ./JavaDoc/org/jhotdraw/samples/net/figures/.*
- ./JavaDoc/org/jhotdraw/samples/odg/.*
- ./JavaDoc/org/jhotdraw/samples/odg/action/.*
- ./JavaDoc/org/jhotdraw/samples/odg/figures/.*
- ./JavaDoc/org/jhotdraw/samples/odg/geom/.*
- ./JavaDoc/org/jhotdraw/samples/odg/io/.*
- ./JavaDoc/org/jhotdraw/samples/pert/.*
- ./JavaDoc/org/jhotdraw/samples/pert/figures/.*
- ./JavaDoc/org/jhotdraw/samples/svg/.*
- ./JavaDoc/org/jhotdraw/samples/svg/action/.*
- ./JavaDoc/org/jhotdraw/samples/svg/figures/.*
- ./JavaDoc/org/jhotdraw/samples/svg/gui/.*
- ./JavaDoc/org/jhotdraw/samples/svg/io/.*
- ./JavaDoc/org/jhotdraw/samples/teddy/.*
- ./JavaDoc/org/jhotdraw/samples/teddy/action/.*
- ./JavaDoc/org/jhotdraw/samples/teddy/io/.*
- ./JavaDoc/org/jhotdraw/samples/teddy/regex/.*
- ./JavaDoc/org/jhotdraw/samples/teddy/text/.*
- ./JavaDoc/org/jhotdraw/text/.*
- ./JavaDoc/org/jhotdraw/undo/.*
- ./JavaDoc/org/jhotdraw/util/.*
- ./JavaDoc/org/jhotdraw/util/prefs/.*
- ./JavaDoc/org/jhotdraw/xml/.*
- ./JavaDoc/org/jhotdraw/xml/css/.*
- ./Samples/.*
- ./Samples/Draw/.*
- ./Samples/Draw/signed/.*
- ./Samples/JHotDraw/.*
- ./Samples/Net/.*
- ./Samples/Net/signed/.*
- ./Samples/PERT/.*
- ./Samples/PERT/signed/.*
- ./Samples/SVG/.*
- ./Samples/SVG/signed/.*
- ./Samples/Teddy/.*
- ./Samples/Teddy/signed/.*
- ./bin/.*
- ./bin/net/.*
- ./bin/net/n3/.*
- ./bin/net/n3/nanoxml/.*
- ./bin/org/.*
- ./bin/org/jhotdraw/.*
- ./bin/org/jhotdraw/annotations/.*
- ./bin/org/jhotdraw/app/.*
- ./bin/org/jhotdraw/app/action/.*
- ./bin/org/jhotdraw/app/action/app/.*
- ./bin/org/jhotdraw/app/action/edit/.*
- ./bin/org/jhotdraw/app/action/file/.*
- ./bin/org/jhotdraw/app/action/images/.*
- ./bin/org/jhotdraw/app/action/view/.*
- ./bin/org/jhotdraw/app/action/window/.*
- ./bin/org/jhotdraw/app/osx/.*
- ./bin/org/jhotdraw/beans/.*
- ./bin/org/jhotdraw/color/.*
- ./bin/org/jhotdraw/color/images/.*
- ./bin/org/jhotdraw/draw/.*
- ./bin/org/jhotdraw/draw/action/.*
- ./bin/org/jhotdraw/draw/action/images/.*
- ./bin/org/jhotdraw/draw/action/images/_notes/.*
- ./bin/org/jhotdraw/draw/connector/.*
- ./bin/org/jhotdraw/draw/decoration/.*
- ./bin/org/jhotdraw/draw/event/.*
- ./bin/org/jhotdraw/draw/handle/.*
- ./bin/org/jhotdraw/draw/io/.*
- ./bin/org/jhotdraw/draw/layouter/.*
- ./bin/org/jhotdraw/draw/liner/.*
- ./bin/org/jhotdraw/draw/locator/.*
- ./bin/org/jhotdraw/draw/print/.*
- ./bin/org/jhotdraw/draw/text/.*
- ./bin/org/jhotdraw/draw/tool/.*
- ./bin/org/jhotdraw/geom/.*
- ./bin/org/jhotdraw/gui/.*
- ./bin/org/jhotdraw/gui/datatransfer/.*
- ./bin/org/jhotdraw/gui/event/.*
- ./bin/org/jhotdraw/gui/filechooser/.*
- ./bin/org/jhotdraw/gui/fontchooser/.*
- ./bin/org/jhotdraw/gui/plaf/.*
- ./bin/org/jhotdraw/gui/plaf/palette/.*
- ./bin/org/jhotdraw/gui/plaf/palette/colorchooser/.*
- ./bin/org/jhotdraw/gui/plaf/palette/images/.*
- ./bin/org/jhotdraw/io/.*
- ./bin/org/jhotdraw/net/.*
- ./bin/org/jhotdraw/samples/.*
- ./bin/org/jhotdraw/samples/color/.*
- ./bin/org/jhotdraw/samples/draw/.*
- ./bin/org/jhotdraw/samples/font/.*
- ./bin/org/jhotdraw/samples/mini/.*
- ./bin/org/jhotdraw/samples/net/.*
- ./bin/org/jhotdraw/samples/net/figures/.*
- ./bin/org/jhotdraw/samples/net/images/.*
- ./bin/org/jhotdraw/samples/odg/.*
- ./bin/org/jhotdraw/samples/odg/action/.*
- ./bin/org/jhotdraw/samples/odg/figures/.*
- ./bin/org/jhotdraw/samples/odg/geom/.*
- ./bin/org/jhotdraw/samples/odg/io/.*
- ./bin/org/jhotdraw/samples/pert/.*
- ./bin/org/jhotdraw/samples/pert/figures/.*
- ./bin/org/jhotdraw/samples/pert/images/.*
- ./bin/org/jhotdraw/samples/svg/.*
- ./bin/org/jhotdraw/samples/svg/action/.*
- ./bin/org/jhotdraw/samples/svg/action/images/.*
- ./bin/org/jhotdraw/samples/svg/figures/.*
- ./bin/org/jhotdraw/samples/svg/gui/.*
- ./bin/org/jhotdraw/samples/svg/io/.*
- ./bin/org/jhotdraw/samples/teddy/.*
- ./bin/org/jhotdraw/samples/teddy/action/.*
- ./bin/org/jhotdraw/samples/teddy/io/.*
- ./bin/org/jhotdraw/samples/teddy/regex/.*
- ./bin/org/jhotdraw/samples/teddy/text/.*
- ./bin/org/jhotdraw/text/.*
- ./bin/org/jhotdraw/undo/.*
- ./bin/org/jhotdraw/undo/images/.*
- ./bin/org/jhotdraw/util/.*
- ./bin/org/jhotdraw/util/prefs/.*
- ./bin/org/jhotdraw/xml/.*
- ./bin/org/jhotdraw/xml/css/.*
- ./lib/.*
